"""add last reminder date

Revision ID: 0232f983c349
Revises: 9c2754fbec52
Create Date: 2026-07-04 13:08:03.096838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0232f983c349'
down_revision: Union[str, Sequence[str], None] = '9c2754fbec52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_reminder_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_reminder_date')
    # ### end Alembic commands ###
