"""add utc_offset

Revision ID: 1e3538730d96
Revises: 88f2b62c305a
Create Date: 2026-07-03 20:15:33.126815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1e3538730d96'
down_revision: Union[str, Sequence[str], None] = '88f2b62c305a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('utc_offset', sa.SmallInteger(), nullable=False))
    op.alter_column('users', 'reminder_time',
               existing_type=mysql.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reminder_time',
               existing_type=mysql.TIME(),
               nullable=True)
    op.drop_column('users', 'utc_offset')
    # ### end Alembic commands ###
