"""add some cols

Revision ID: 4a93a4867f71
Revises: 0232f983c349
Create Date: 2026-07-11 16:31:39.663119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a93a4867f71'
down_revision: Union[str, Sequence[str], None] = '0232f983c349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep_records', sa.Column('sleep_end', sa.Time(), nullable=False))
    op.add_column('sleep_records', sa.Column('sleep_rating', sa.SmallInteger(), nullable=False))
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_enabled')
    op.drop_column('sleep_records', 'sleep_rating')
    op.drop_column('sleep_records', 'sleep_end')
    # ### end Alembic commands ###
